framework:
    # default_locale utilisera cette langue par défault
    default_locale: fr
    translator:
        default_path: '%kernel.project_dir%/translations'
        # fallbacks définit la langue par défaut , ici c'est fr, pour français
        fallbacks:
            - fr
